version: '3.8'

services:
  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - NODE_ENV=${AUTH_SERVICE_NODE_ENV}
      - DB_HOST=${AUTH_SERVICE_DB_HOST}
      - DB_PORT=${AUTH_SERVICE_DB_PORT}
      - DB_USER=${AUTH_SERVICE_DB_USER}
      - DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - DB_NAME=${MYSQL_AUTH_DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: ["/usr/src/app/wait-for-it.sh", "${AUTH_SERVICE_DB_HOST}", "${AUTH_SERVICE_DB_PORT}", "--", "npm", "start"]
    healthcheck:
      test: ["CMD-SHELL", "/usr/src/app/healthcheck.sh"]
      interval: 5s
      timeout: 20s
      retries: 5

  # Shop Service
  shop-service:
    build:
      context: ./services/shop-service
      dockerfile: Dockerfile
    ports:
      - "${SHOP_SERVICE_PORT}:${SHOP_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${SHOP_SERVICE_NODE_ENV}
      - PORT=${SHOP_SERVICE_PORT}
      - DB_HOST=${SHOP_SERVICE_DB_HOST}
      - DB_PORT=${SHOP_SERVICE_DB_PORT}
      - DB_USER=${SHOP_SERVICE_DB_USER}
      - DB_PASSWORD=${SHOP_SERVICE_DB_PASSWORD}
      - DB_NAME=${SHOP_SERVICE_DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SHOP_SERVICE_URL=http://shop-service:${SHOP_SERVICE_PORT}
    depends_on:
      mysql:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - app-network
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD-SHELL", "/usr/src/app/healthcheck.sh"]
      interval: 5s
      timeout: 20s
      retries: 5

  # MySQL Database Service
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Parser Service
  # parser-service:
  #   build:
  #     context: ./parser-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${PARSER_SERVICE_PORT}:${PARSER_SERVICE_PORT}"
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=${PARSER_SERVICE_NODE_ENV}
  #     - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
  #   depends_on:
  #     auth-service:
  #       condition: service_healthy
  #   networks:
  #     - app-network
  #   command: ["npm", "start"]

  # Frontend
  # frontend:
  #   build:
  #     context: ./services/frontend-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - app-network
  #   depends_on:
  #     shop-service:
  #       condition: service_healthy
  #   environment:
  #     - REACT_APP_API_URL=http://shop-service:3003

  # Social Network Service
  social-network-service:
    build:
      context: ./services/social-network-service
      dockerfile: Dockerfile
    ports:
      - "${SOCIAL_NETWORK_SERVICE_PORT}:${SOCIAL_NETWORK_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${SOCIAL_NETWORK_SERVICE_NODE_ENV}
      - PORT=${SOCIAL_NETWORK_SERVICE_PORT}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_SOCIAL_NETWORK_DB}?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - app-network
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:${SOCIAL_NETWORK_SERVICE_PORT}/health || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 5

  # MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_SOCIAL_NETWORK_DB} # Optional, creates a default database
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 })' --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  mongodb_data:

networks:
  app-network:
