name: Deploy to AWS

on:
  push:
    branches:
      - main         # Deploy when changes are pushed to the main branch (Production)
      - deployment   # Deploy when changes are pushed to the deployment branch (Development)

jobs:
  deploy:
    name: Deploy Services and Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      TF_WORKING_DIR: infrastructure

    steps:
      # Print Environment Variables (Debugging)
      - name: Print all environment variables
        run: printenv

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set Environment Variables Based on Branch
      - name: Set Environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_ENV
            echo "tfvars_file=prod.tfvars" >> $GITHUB_ENV
          else
            echo "env_name=dev" >> $GITHUB_ENV
            echo "tfvars_file=dev.tfvars" >> $GITHUB_ENV
          fi

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies for Services
      - name: Install Dependencies for Services
        working-directory: services
        run: |
          cd auth-service && npm install && npm run build
          cd ../shop-service && npm install && npm run build

      # Package Lambda Functions for Deployment
      - name: Package Lambda Functions
        working-directory: services
        run: |
          # Auth Service
          cd auth-service
          npm install --only=production
          zip -r auth-service.zip index.js node_modules package.json
          mv auth-service.zip ../../infrastructure/lambda/auth-service.zip
          cd ../shop-service
          # Shop Service
          npm install --only=production
          zip -r shop-service.zip index.js node_modules package.json
          mv shop-service.zip ../../infrastructure/lambda/shop-service.zip

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # Clean Up Existing State (Optional for Fresh Deployments)
      - name: Clean Up Terraform State
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform state rm aws_iam_role.auth-service_execution_role || true
          terraform state rm aws_iam_role.shop-service_execution_role || true

      # Conditional Terraform Destroy for Non-Production
      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var-file=env/${{ env.tfvars_file }}

      # Validate Terraform Configuration
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file=env/${{ env.tfvars_file }}

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -var-file=env/${{ env.tfvars_file }}

      # Verify Deployment
      - name: Verify Deployment
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "API Gateway URL:"
          terraform output -raw api_gateway_url
